git:
    submodules: false

notifications:
    email: false

language: generic

before_install:
    - sudo apt update
    - sudo apt install nodejs npm
    - sudo pip install --upgrade pip
    - sudo pip install Sphinx
    - sudo pip install sphinxcontrib-inlinesyntaxhighlight
    - sudo apt install texlive-latex-base
    - git clone https://github.com/FreeFem/FreeFem-parser-pygments.git ~/pygments
    - sudo cp ~/pygments/freefem.py /usr/local/lib/python2.7/dist-packages/pygments/lexers/
    - cd /usr/local/lib/python2.7/dist-packages/pygments/lexers/ && sudo python _mapping.py
    - cd /home/travis/build/FreeFem/FreeFem-doc2

script:
    - make html
    - make latex
    # - cd build/latex && pdflatex -interaction=nonstopmode FreeFem++.tex && pdflatex -interaction=nonstopmode FreeFem++.tex
    - cp -R build/html ..
    # - cp -R build/latex ..

after_success:
    - git config user.name "Travis CI"
    - git config user.email "simon.garnotel@gmail.com"
    - git remote add token "https://${GH_TOKEN}@github.com/FreeFem/FreeFem-doc2.git"
    - git fetch token && git fetch token gh-pages:gh-pages
    - git checkout gh-pages && git clean -f && cp ../html/ ./ && git commit -m"update Web" && git push
    # - git fetch token && git fetch token pdf:pdf
    # - git checkout pdf && git clean -f && cp ../latex/FreeFem++.pdf ./ && git commit -m"update PDF" && git push
