git:
    submodules: false

dist: xenial
language: python

before_install:
    - pip install Sphinx
    - pip install sphinxcontrib-inlinesyntaxhighlight
    - apt install textlive-base
    - git clone https://github.com/FreeFem/FreeFem-parser-pygments.git ~/pygments
    - sudo cp ~/pygments/freefem.py /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pygments/lexers/
    - cd /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pygments/lexers/ && sudo python _mapping.py
    - cd /home/travis/build/FreeFem/FreeFem-doc2

script:
    - make html
    - make latex
