version: 2.1

jobs:
   build:
      machine:
         image: circleci/classic

      working_directory: ~/FreeFem-doc2

      steps:
         - run: sudo apt install python3-pip texlive npm
         - run: sudo pip install Sphinx sphinxcontrib-inlinesyntaxhighlight
         - run: make html
