version: 2.0

jobs:
   build:
      machine:
         image: circleci/classic

      working_directory: ~/FreeFem-doc2

      branches:
         only:
            - master

      steps:
         - checkout
         - run: sudo apt install python3-pip texlive npm
         - run: sudo pip install Sphinx sphinxcontrib-inlinesyntaxhighlight pygments
         - run: sudo find / -name "pygments"
         - run: make html
         - run: make latex
            && cd build/latex
            && pdflatex FreeFem++.tex
            && pdflatex FreeFem++.tex


# - run: git clone https://github.com/FreeFem/FreeFem-parser-pygments.git FreeFem-parser-pygments
#    && sudo cp FreeFem-parser-pygments/freefem.py /opt/google-cloud-sdk/lib/third_party/pygments/lexers
#    && cd /opt/google-cloud-sdk/lib/third_party/pygments/lexers
#    && sudo python _mapping.py
